#!/bin/sh
#
# UniNav website generation script
#

echo "Publishing website, please wait..."

cd /var/transas/www || exit
unset GIT_DIR
git reset --hard HEAD >/dev/null 2>&1
find . -name '*.html'|xargs rm -rf >/dev/null 2>&1
git pull origin master >/dev/null 2>&1
emacs --batch -l /home/git/.emacs.d/init.el -l /home/git/repositories/uninav-page-muse.git/hooks/uninav-page-muse.el -f muse-project-batch-publish "uninav-page" >/dev/null 2>&1

exec git update-server-info
